project_id = "jstqb-study-app"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = ["jstqbstudy://**"]
jwt_expiry = 3600
enable_signup = true
